<?php

namespace App\Enums;

class AccionsEnums
{
    
    public const ADD_PERMIT='ADD';
    public const UPDATE_PERMIT='UPDATE';
    public const READ_PERMIT='READ';
    public const DELETE_PERMIT='DELETE';
    public const ADD_PRODUCTO_PERMIT='ADD_PRODUCTOS';
    public const ADD_EQUIVALENCIA_PERMIT='ADD_EQUIVALENCIA';
    public const ADD_CATEGORIA_PERMIT='ADD_CATEGORIA';
    public const ADD_ATRIBUTO_PERMIT='ADD_ATRIBUTO';
    public const ADD_MARCA_PERMIT='ADD_MARCA';
    public const ADD_PROVEEDOR_PERMIT='ADD_PROVEEDOR';
    public const ADD_COSTOS_PERMIT='ADD_COSTOS';
    public const ADD_LISTAPRECIOS_PERMIT='ADD_LISTAPRECIOS';
    public const UPDATE_PRODUCTOS_PERMIT='UPDATE_PRODUCTOS';
    public const UPDATE_EQUIVALENCIA_PERMIT='UPDATE_EQUIVALENCIA';
    public const UPDATE_CATEGORIA_PERMIT='UPDATE_CATEGORIA';
    public const UPDATE_ATRIBUTO_PERMIT='UPDATE_ATRIBUTO';
    public const UPDATE_MARCA_PERMIT='UPDATE_MARCA';
    public const UPDATE_PROVEEDOR_PERMIT='UPDATE_PROVEEDOR';
    public const UPDATE_COSTOS_PERMIT='UPDATE_COSTOS';
    public const UPDATE_LISTAPRECIOS_PERMIT='UPDATE_LISTAPRECIOS';
    public const DELETE_PRODUCTOS_PERMIT='DELETE_PRODUCTOS';
    public const DELETE_EQUIVALENCIA_PERMIT='DELETE_EQUIVALENCIA';
    public const DELETE_CATEGORIA_PERMIT='DELETE_CATEGORIA';
    public const DELETE_ATRIBUTO_PERMIT='DELETE_ATRIBUTO';
    public const DELETE_MARCA_PERMIT='DELETE_MARCA';
    public const DELETE_PROVEEDOR_PERMIT='DELETE_PROVEEDOR';
    public const DELETE_COSTOS_PERMIT='DELETE_COSTOS';
    public const DELETE_LISTAPRECIOS_PERMIT='DELETE_LISTAPRECIOS';
    public const READ_PRODUCTOS_PERMIT='READ_PRODUCTOS';
    public const READ_EQUIVALENCIA_PERMIT='READ_EQUIVALENCIA';
    public const READ_CATEGORIA_PERMIT='READ_CATEGORIA';
    public const READ_ATRIBUTO_PERMIT='READ_ATRIBUTO';
    public const READ_MARCA_PERMIT='READ_MARCA';
    public const READ_PROVEEDOR_PERMIT='READ_PROVEEDOR';
    public const READ_COSTOS_PERMIT='READ_COSTOS';
    public const READ_LISTAPRECIOS_PERMIT='READ_LISTAPRECIOS';

    public const ADMIN_PERMITS =[self::ADD_PERMIT,self::UPDATE_PERMIT,self::DELETE_PERMIT,self::READ_PERMIT];
    
}
